### ISSUE TITLE
Vergeml doesn't work

### ISSUE THREAD

**Issue by pagdot** [vergeml/vergeml#8]
After installing VergeML 0.1.4 via pip with

    pip install vergeml

I get following error when executing it:

```
$ ml
Traceback (most recent call last):
  File "/usr/local/bin/ml", line 6, in <module>
    from vergeml.__main__ import main
  File "/usr/local/lib/python3.5/dist-packages/vergeml/__init__.py", line 4, in <module>
    from vergeml.utils import VergeMLError
  File "/usr/local/lib/python3.5/dist-packages/vergeml/utils.py", line 167
    npath = f"{path}.{k}" if path is not None else k
                        ^
SyntaxError: invalid syntax
```

**Comment by mme** [comment]
Please run:

`python --version`

What's the output?

**Comment by pagdot** [comment]
```
$ python --version
Python 2.7.12

$ python3 --version
Python 3.5.2
```

I also installed tried installing it using pip3, but it doens't work either.

**Comment by mme** [comment]
You installed it correctly, but the `ml` script will use your system version.

You can set your main python executable to be version 3 temporarily like this:

```
$ alias python=python3

$ ml --help # should work now
```

For a more permanent solution you can:
- make your system default to version 3 if possible
- use miniconda to manage a separate environment: https://docs.conda.io/en/latest/miniconda.html

**Comment by pagdot** [comment]
I found the problem. I had a too old (and maybe broken python + pip) installation. Thanks for your help
